version: 2

models:
  - name: stg_tech_stocks
    config:
      materialized: table
      schema: MARKET_DATA
    description: Cleaned tech stock data
    columns:
      - name: symbol
        description: Stock symbol
      - name: date
        description: Trading date
      - name: opening_price
        description: Opening price
      - name: high_price
        description: High price
      - name: low_price
        description: Low price
      - name: closing_price
        description: Closing price
      - name: volume
        description: Trading volume
      - name: relative_strength_index
        description: RSI value

  - name: stg_gdp
    config:
      materialized: table
      schema: MARKET_DATA
    description: Cleaned GDP data
    columns:
      - name: gdp_date
        description: GDP reporting date
      - name: gdp_value
        description: GDP value
      - name: load_timestamp
        description: Timestamp when data was loaded
