-- Create warehouse if it doesn't exist
CREATE WAREHOUSE IF NOT EXISTS STOCKS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS STOCKS_DB;

-- Use the new database
USE DATABASE STOCKS_DB;

-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS MARKET_DATA;

-- Grant privileges to your user (replace YOUR_USER with your Snowflake username)
GRANT ALL PRIVILEGES ON WAREHOUSE STOCKS_WH TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON DATABASE STOCKS_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE STOCKS_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE STOCKS_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE STOCKS_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE STOCKS_DB TO ROLE SYSADMIN;

-- Set up the default warehouse, database, and schema
USE WAREHOUSE STOCKS_WH;
USE DATABASE STOCKS_DB;
USE SCHEMA MARKET_DATA;
